### ISSUE TITLE
how to generate the Output file: [genes|transcripts]_data_per_samples.txt ?

### ISSUE THREAD

**Issue by kmeusemann** [ncbi/TPMCalculator#55]
Hi, 

running TPMCalculator installed with bioconda) on a directory: how do I get / create the output file as described in the "Outputr file section"?
command I used:

TPMCalculator -g GENOME.gtf -d BAMS/ -e
-> with all bam files in the filder BAM.

It worked fine :

Reading GTF file ... 
Done in 8.92957 seconds
Parsing BAM files
...
Printing results

BUT I did not find in the usage then how to create the 
Output file: [genes|transcripts]_data_per_samples.txt

Any help appreiated!!

Cheers Karen

**Comment by kmeusemann** [comment]
Dear TPMcalculator team,
its qiuite urgent s any hints much appreciated!
best Karen

**Comment by r78v10a07** [comment]
Hi,
You can use this simple python script to create the matrix file.
Execute it on the folder with all TPMCalculator results.
It will process the _sorted_genes.out files. If you want to process any other file just change the suffix in the script.

[tpmcalculator2matrixes.py.gz](https://github.com/ncbi/TPMCalculator/files/4965884/tpmcalculator2matrixes.py.gz)

**Comment by r78v10a07** [comment]
Did you solve the problem with the script I sent?

**Comment by alexbougdour** [comment]
Hi,
I've tested the tpmcalculator2matrixes.py.gz script without any success.
Alex

**Comment by r78v10a07** [comment]
What are the errors?
What are your input files?

**Comment by alexbougdour** [comment]
Here is was I got:

(tpmcalculator) alexandre@alexandre-Precision-Tower-5810:~/Documents/Spombe_data_tmp$ python tpmcalculator2matrixes.py
ExonTPM
Data columns: 0
Data rows: 0
Traceback (most recent call last):
  File "/home/alexandre/miniconda3/envs/tpmcalculator/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Gene_Id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tpmcalculator2matrixes.py", line 29, in <module>
    data[column]['Gene_Chr_Start'] = data[column]['Gene_Id'] + '_' + data[column]["Chr"] + '_' + data[column]["Start"].map(str)
  File "/home/alexandre/miniconda3/envs/tpmcalculator/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/alexandre/miniconda3/envs/tpmcalculator/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'Gene_Id'

**Comment by alexbougdour** [comment]
The input files were 
Here is was I got:

(tpmcalculator) alexandre@alexandre-Precision-Tower-5810:~/Documents/Spombe_data_tmp$ python tpmcalculator2matrixes.py
ExonTPM
Data columns: 0
Data rows: 0
Traceback (most recent call last):
  File "/home/alexandre/miniconda3/envs/tpmcalculator/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Gene_Id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tpmcalculator2matrixes.py", line 29, in <module>
    data[column]['Gene_Chr_Start'] = data[column]['Gene_Id'] + '_' + data[column]["Chr"] + '_' + data[column]["Start"].map(str)
  File "/home/alexandre/miniconda3/envs/tpmcalculator/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/alexandre/miniconda3/envs/tpmcalculator/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'Gene_Id'

**Comment by r78v10a07** [comment]
Hi, 
The attached script is a very simple python script that you need to modify a bit to make it work with your output files name. I created a modified version that may work.

The script works with the _genes.out files (compressed or not) expect files like this:

```bash
sample1_genes.out.gz
sample2_genes.out.gz
sample3_genes.out.gz
```

It will generate a matrix for the ExonTPM values with these columns:
```bash
Gene_Chr_Start   Chr   Start   End   ExonLength   sample1   sample2   sample3   
```
and another similar for the exon reads:
```bash
Gene_Chr_Start   Chr   Start   End   ExonLength   sample1   sample2   sample3   
```
[tpmcalculator2matrixes.py.gz](https://github.com/ncbi/TPMCalculator/files/5267739/tpmcalculator2matrixes.py.gz)

Please, try and let me know.

**Comment by alexbougdour** [comment]
Thanks a lot ! It works just fine.
Is there any way to keep the sample's name in the header?
Alex

**Comment by r78v10a07** [comment]
It uses file name as sample name.

**Comment by venkan** [comment]
Hi Roberto and Alex,

I have _genes.out files in a folder like below:

```
Sample1.sorted_genes.out
Sample2.sorted_genes.out
Sample3.sorted_genes.out
```
And I have this python code:

```
import os
import pandas

data = {}
columns = ['ExonTPM', 'ExonReads']
output_suffix = "_genes.out"
files = [ f for ds, df, files in os.walk('./') for f in files if output_suffix in f]
for column in columns:
    print(column)
    data[column] = pandas.DataFrame()
    for f in files:
        # Get sample name removing the suffix and check if the output is compressed
        if f.endswith('.gz'):
            output_suffix_real = output_suffix + '.gz'
        else:
            output_suffix_real = output_suffix
        s = f.replace(output_suffix_real, '')
        df = pandas.read_csv(f, sep='\t')
        df = df[['Gene_Id', 'Chr', 'Start', 'End', 'ExonLength', column]]
        df = df.rename(index=str, columns={column: s})
        if data[column].empty:
            data[column] = df
        else:
            data[column] = data[column].merge(df, on=['Gene_Id', 'Chr', 'Start', 'End', 'ExonLength'], how='outer')
    print('Data columns: ' + str(len(data[column].columns)))
    print('Data rows: ' + str(len(data[column])))

    # Printing TSV matrices
    data[column]['Gene_Chr_Start'] = data[column]['Gene_Id'] + '_' + data[column]["Chr"] + '_' + data[column]["Start"].map(str)
    data[column] = data[column].drop(['Gene_Id'], axis=1)
    cols = data[column].columns.tolist()
    cols = cols[-1:] + cols[:-1]
    data[column] = data[column][cols]
    data[column].to_csv( column + '.tsv', sep='\t', index=False, na_rep='0')
```

I used `python3 tpmcalculator2matrixes.py`

This gave an Error like below:

```
ExonTPM
sys:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
Data columns: 8
Data rows: 49773
Traceback (most recent call last):
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1505, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1529, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1507, in na_op
    result = masked_arith_op(x, y, op)
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1009, in masked_arith_op
    com.values_from_object(yrav[mask]))
TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tpmcalculator2matrixes.py", line 29, in <module>
    data[column]['Gene_Chr_Start'] = data[column]['Gene_Id'] + '_' + data[column]["Chr"] + '_' + data[column]["Start"].map(str)
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1583, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1533, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas/_libs/algos.pyx", line 690, in pandas._libs.algos.arrmap
  File "/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/site-packages/pandas-0.24.2-py3.7-linux-x86_64.egg/pandas/core/ops.py", line 1533, in <lambda>
    lambda x: op(x, rvalues))
TypeError: can only concatenate str (not "int") to str
```

May I know what could be the issue?

**Comment by r78v10a07** [comment]
Hi,
Are your chromosomes names or gene names only numbers?
Change line 30 to:

```
data[column]['Gene_Chr_Start']` = data[column]['Gene_Id'].map(str) + '_' + data[column]["Chr"].map(str) + '_' + data[column]["Start"].map(str)
```

Let me know if this works.

**Comment by venkan** [comment]
@r78v10a07 Thanks a lot Roberto. It worked.
